Repository prgrms-be-devcourse/NBB1_1_3_Team04, pull requests merged in 2024-10, with the labels that each got.

#3 [Feat/#1] 채팅 엔티티 구현
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/domain/Chat.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/domain/ChatMember.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/domain/ChatType.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/domain/Chatroom.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/domain/ReservationChatroom.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/domain/TeamChatroom.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/config/websocket/StompHandler.java
  src/main/kotlin/com/grepp/nbe1_3_team04/config/websocket/WebSocketConfig.java
  src/main/kotlin/com/grepp/nbe1_3_team04/global/exception/ExceptionHandlerFilter.java
  src/main/kotlin/com/grepp/nbe1_3_team04/global/exception/ExceptionMessage.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/domain/Member.kt
Labels: ✨Feature, 황민우

#5 [Feat/#2] 풋살장 엔티티 구현
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/domain/Court.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/domain/Position.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/domain/Stadium.kt
Labels: ✨Feature, 노관태

#7 [Feat] 투표 관련 엔티티 마이그레이션
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/domain/Choice.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/domain/Vote.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/domain/VoteItem.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/domain/VoteItemDate.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/domain/VoteItemLocate.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/domain/VoteStatus.kt
  src/test/kotlin/com/grepp/nbe1_3_team04/vote/domain/VoteItemDateTest.kt
  src/test/kotlin/com/grepp/nbe1_3_team04/vote/domain/VoteTest.kt
Labels: ✨Feature, 나민혁

#10 [Feat/#4] 예약 관련 엔티티 마이그레이션
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/domain/Chat.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/domain/ChatMember.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/domain/Chatroom.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/domain/Game.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/domain/GameStatus.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/domain/Mercenary.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/domain/Participant.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/domain/ParticipantGender.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/domain/ParticipantRole.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/domain/Reservation.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/domain/ReservationStatus.kt
Labels: ✨Feature, 황민우

#9 feat: #8 팀 관련 엔티티 마이그레이션
  src/main/kotlin/com/grepp/nbe1_3_team04/team/domain/Team.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/team/domain/TeamMember.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/team/domain/TeamMemberRole.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/team/domain/TeamRate.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/team/domain/TotalRecord.kt
Labels: ✨Feature, 박윤영

#17 [refactor/#8] 코드 리뷰 적용
  src/main/kotlin/com/grepp/nbe1_3_team04/team/domain/Team.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/team/domain/TeamMember.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/team/domain/TeamRate.kt
Labels: 🔨Refactor, 박윤영

#14 [Feat/#12] 채팅 관련 리포지토리 마이그레이션
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/domain/Chat.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/repository/ChatMemberRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/repository/ChatRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/repository/ChatroomRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/repository/CustomChatMemberRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/repository/CustomChatMemberRepositoryImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/repository/CustomChatRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/repository/CustomChatRepositoryImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/repository/RedisChatroomRepository.kt
Labels: ✨Feature, 황민우

#16 [feat/#15] 채팅 event 마이그레이션
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/event/ReservationDeletedEvent.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/event/ReservationMemberJoinEvent.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/event/ReservationMemberLeaveEvent.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/event/ReservationMembersJoinEvent.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/event/ReservationPublishedEvent.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/event/TeamDeletedEvent.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/event/TeamMemberJoinEvent.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/event/TeamMemberLeaveEvent.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/event/TeamMembersJoinEvent.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/event/TeamPublishedEvent.kt
Labels: ✨Feature, 황민우

#13 [Feat/#11] 채팅 관련 DTO 마이그레이션
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/api/request/ChatMemberRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/api/request/ChatRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/api/request/ChatUpdateRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/api/request/ChatroomRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/request/ChatMemberServiceRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/request/ChatServiceRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/request/ChatUpdateServiceRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/request/ChatroomServiceRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/response/ChatMemberInfo.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/response/ChatMemberResponse.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/response/ChatResponse.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/response/ChatroomResponse.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/global/exception/ExceptionMessage.kt
Labels: ✨Feature, 황민우

#20 [Feat/#18] jwt 마이그레이션
  build.gradle.kts
  src/main/kotlin/com/grepp/nbe1_3_team04/member/jwt/JwtTokenFilter.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/jwt/JwtTokenUtil.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/jwt/PrincipalDetails.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/jwt/PrincipalDetailsService.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/jwt/response/TokenResponse.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/repository/CustomMemberRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/repository/CustomMemberRepositoryImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/repository/MemberRepository.kt
Labels: ✨Feature, 문재경

#23 [Feat] 투표 도메인 DTO 마이그레이션
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/domain/Reservation.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/api/request/ChoiceCreateRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/api/request/CourtChoices.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/api/request/DateChoices.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/api/request/VoteCourtCreateRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/api/request/VoteDateCreateRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/api/request/VoteUpdateRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/api/request/annotation/Duplicate.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/api/request/annotation/validator/DuplicateValidator.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/service/request/ChoiceCreateServiceRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/service/request/VoteCourtCreateServiceRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/service/request/VoteDateCreateServiceRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/service/request/VoteUpdateServiceRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/service/response/AllVoteResponse.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/service/response/VoteItemResponse.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/service/response/VoteResponse.kt
Labels: ✨Feature, 나민혁

#29 [Feat: #25] 팀 DTO 코틀린 마이그레이션
  src/main/kotlin/com/grepp/nbe1_3_team04/team/api/request/TeamCreateRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/team/api/request/TeamMemberRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/team/api/request/TeamUpdateRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/team/domain/TeamMember.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/team/domain/TotalRecord.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/team/service/request/TeamDefaultServiceRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/team/service/request/TeamMemberServiceRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/team/service/response/TeamDefaultResponse.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/team/service/response/TeamInfoResponse.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/team/service/response/TeamResponse.kt
Labels: ✨Feature, 박윤영

#30 [Feat/#19] global 패키지 마이그레이션
  src/main/kotlin/com/grepp/nbe1_3_team04/global/api/ApiResponse.java
  src/main/kotlin/com/grepp/nbe1_3_team04/global/api/ApiResponse.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/global/exception/ExceptionHandlerFilter.java
  src/main/kotlin/com/grepp/nbe1_3_team04/global/exception/ExceptionHandlerFilter.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/global/exception/GlobalExceptionHandler.java
  src/main/kotlin/com/grepp/nbe1_3_team04/global/exception/GlobalExceptionHandler.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/global/repository/CustomGlobalRepository.java
  src/main/kotlin/com/grepp/nbe1_3_team04/global/repository/CustomGlobalRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/repository/MemberRepository.kt
Labels: ✨Feature, 노관태

#33 [Feat#24] 레포지토리 마이그레이션
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/repository/ChoiceRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/repository/CustomChoiceRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/repository/CustomChoiceRepositoryImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/repository/CustomVoteRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/repository/CustomVoteRepositoryImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/repository/VoteItemRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/repository/VoteRepository.kt
Labels: ✨Feature, 나민혁

#34 [Feat/#27] 풋살장 DTO 마이그레이션
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/api/request/CourtDeleteRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/api/request/CourtRegisterRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/api/request/CourtUpdateRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/api/request/StadiumRegisterRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/api/request/StadiumSearchByLocationRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/api/request/StadiumUpdateRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/api/request/validation/CourtAllowedValues.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/api/request/validation/CourtAllowedValuesValidator.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/api/request/validation/StadiumAllowedValues.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/api/request/validation/StadiumAllowedValuesValidator.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/service/request/CourtDeleteServiceRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/service/request/CourtRegisterServiceRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/service/request/CourtUpdateServiceRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/service/request/StadiumRegisterServiceRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/service/request/StadiumSearchByLocationServiceRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/service/request/StadiumUpdateServiceRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/service/response/CourtDetailResponse.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/service/response/CourtsResponse.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/service/response/StadiumDetailResponse.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/service/response/StadiumsResponse.kt
Labels: ✨Feature, 노관태

#39 [Feat/#32] reservation 관련 리포지토리 마이그레이션
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/repository/CustomChatMemberRepositoryImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/repository/CustomChatRepositoryImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/repository/CustomMercenaryRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/repository/CustomMercenaryRepositoryImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/repository/CustomParticipantRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/repository/CustomParticipantRepositoryImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/repository/GameRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/repository/MercenaryRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/repository/ParticipantRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/repository/ReservationRepository.kt
Labels: ✨Feature, 황민우

#41 [Fix/#40] security oauth 오류 수정
  src/main/kotlin/com/grepp/nbe1_3_team04/config/SecurityConfig.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/oauth2/CustomOAuth2UserDetails.kt
Labels: 🔥BugFix, 문재경

#44 [Feat/#43] config 마이그레이션
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/repository/RedisChatroomRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/RedisSubscriber.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/config/AsyncConfig.java
  src/main/kotlin/com/grepp/nbe1_3_team04/config/AsyncConfig.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/config/JpaAuditingConfig.java
  src/main/kotlin/com/grepp/nbe1_3_team04/config/JpaAuditingConfig.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/config/QueryDslConfig.java
  src/main/kotlin/com/grepp/nbe1_3_team04/config/QueryDslConfig.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/config/SchedulingConfig.java
  src/main/kotlin/com/grepp/nbe1_3_team04/config/SchedulingConfig.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/config/SecurityConfig.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/config/redis/RedisConfig.java
  src/main/kotlin/com/grepp/nbe1_3_team04/config/redis/RedisConfig.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/config/websocket/StompHandler.java
  src/main/kotlin/com/grepp/nbe1_3_team04/config/websocket/StompHandler.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/config/websocket/WebSocketConfig.java
  src/main/kotlin/com/grepp/nbe1_3_team04/config/websocket/WebSocketConfig.kt
Labels: ✨Feature, 문재경

#37 [refactor: #25] 팀 DTO 누락된 코드 리팩토링 적용
  src/main/kotlin/com/grepp/nbe1_3_team04/team/api/request/TeamCreateRequest.kt
Labels: 🔨Refactor, 박윤영

#45 [Feat/#28] 풋살장 repository 마이그레이션
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/api/request/CourtRegisterRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/api/request/CourtUpdateRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/repository/CourtRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/repository/CustomCourtRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/repository/CustomCourtRepositoryImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/repository/CustomStadiumRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/repository/CustomStadiumRepositoryImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/repository/StadiumRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/service/request/CourtRegisterServiceRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/service/request/CourtUpdateServiceRequest.kt
Labels: ✨Feature, 노관태

#50 [Feat#42] 서비스 인터페이스, 컨트롤러 마이그레이션
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/api/ChoiceApi.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/api/VoteApi.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/service/VoteService.kt
Labels: ✨Feature, 나민혁

#48 [Feat/#36] 멤버 DTO 마이그레이션
  src/main/kotlin/com/grepp/nbe1_3_team04/member/api/request/JoinRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/api/request/LoginRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/api/request/UpdatePasswordRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/api/request/UpdateRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/api/request/validation/PasswordMatches.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/api/request/validation/PasswordMatchesValidator.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/domain/Member.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/jwt/PrincipalDetails.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/service/request/JoinServiceRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/service/request/LoginServiceRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/service/request/UpdatePasswordServiceRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/service/request/UpdateServiceRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/service/response/MemberResponse.kt
Labels: ✨Feature, 문재경

#52 [Feat/#47] 풋살장 서비스 인터페이스, 컨트롤러 마이그레이션
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/api/CourtApi.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/api/CourtMerchantApi.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/api/StadiumApi.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/api/StadiumMerchantApi.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/service/CourtService.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/service/StadiumService.kt
Labels: ✨Feature, 노관태

#58 [feat/#56] 투표 서비스 구현체 마이그레이션
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/api/VoteApi.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/service/EndVoteEvent.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/service/RegisteredVoteEvent.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/service/VoteEventHandler.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/service/VoteService.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/vote/service/VoteServiceImpl.kt
Labels: ✨Feature, 나민혁

#59 [Feat/#54] 팀 서비스, 컨트롤러 마이그레이션
  src/main/kotlin/com/grepp/nbe1_3_team04/team/api/TeamApi.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/team/api/TeamMemberApi.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/team/api/TeamRateApi.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/team/service/TeamMemberService.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/team/service/TeamRateService.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/team/service/TeamService.kt
Labels: ✨Feature, 박윤영

#63 [Feat/#62] 예약 서비스 인터페이스 및 컨트롤러 마이그레이션
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/api/GameApi.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/api/MercenaryApi.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/api/ParticipantApi.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/api/ReservationApi.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/service/GameService.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/service/MercenaryService.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/service/ParticipantService.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/service/ReservationService.kt
Labels: ✨Feature, 황민우

#60 [Feat/#57] 풋살장 서비스 구현체 마이그레이션
  src/main/kotlin/com/grepp/nbe1_3_team04/global/exception/ExceptionMessage.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/service/CourtService.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/service/CourtServiceImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/service/StadiumService.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/service/StadiumServiceImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/util/SortFieldMapper.kt
Labels: ✨Feature, 노관태

#64 [Feat/#51] 멤버 서비스-컨트롤러 마이그레이션
  src/main/kotlin/com/grepp/nbe1_3_team04/member/api/MemberApi.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/jwt/response/TokenResponse.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/service/MemberService.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/service/MemberServiceImpl.kt
Labels: ✨Feature, 문재경

#61 [Feat/#55] 채팅 관련 서비스 구현체 마이그레이션
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/ChatMemberService.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/ChatMemberServiceImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/ChatService.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/ChatServiceImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/ChatroomService.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/ChatroomServiceImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/RedisPublisher.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/event/ChatEventListener.kt
Labels: ✨Feature, 황민우

#69 [Feat/#65] 팀 서비스 구현체 마이그레이션
  src/main/kotlin/com/grepp/nbe1_3_team04/team/service/TeamMemberService.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/team/service/TeamMemberServiceImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/team/service/TeamRateServiceImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/team/service/TeamService.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/team/service/TeamServiceImpl.kt
Labels: ✨Feature, 박윤영

#67 [docs/#66] readme 추가
  README.md
Labels: 📃Docs

#70 [Feat/#68] 예약 관련 서비스 마이그레이션
  src/main/kotlin/com/grepp/nbe1_3_team04/global/exception/CustomException.java
  src/main/kotlin/com/grepp/nbe1_3_team04/global/exception/CustomException.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/api/ReservationApi.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/api/request/ReservationUpdateRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/domain/Reservation.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/repository/GameRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/repository/ReservationRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/service/GameServiceImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/service/MercenaryService.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/service/MercenaryServiceImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/service/ParticipantService.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/service/ParticipantServiceImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/service/ReservationService.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/service/ReservationServiceImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/service/request/ReservationUpdateServiceRequest.kt
Labels: ✨Feature, 나민혁, 노관태, 황민우

#74 [fix: #72] : Security 에러 처리
  src/main/kotlin/com/grepp/nbe1_3_team04/config/SecurityConfig.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/global/domain/BaseEntity.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/global/exception/ExceptionHandlerFilter.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/api/request/JoinRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/jwt/JwtTokenFilter.kt
Labels: 🔥BugFix, 문재경

#75 [feat: #71] 채팅방 조회 기능 추가
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/api/ChatroomApi.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/ChatroomService.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/ChatroomServiceImpl.kt
Labels: ✨Feature, 황민우

#76 [fix#73] 참조 타입 변환
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/repository/CustomStadiumRepositoryImpl.kt
Labels: 🔥BugFix, 노관태

#81 [feat/#79] 예약 이벤트 핸들러 마이그레이션
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/service/ReservationEventHandler.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/service/ReservationServiceImpl.kt
Labels: ✨Feature, 나민혁

#80 [Feat/#77] RedisConfig 마이그레이션
  src/main/kotlin/com/grepp/nbe1_3_team04/config/redis/EmbeddedRedisConfig.java
  src/main/kotlin/com/grepp/nbe1_3_team04/config/redis/EmbeddedRedisConfig.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/config/redis/ExternalRedisConfig.java
  src/main/kotlin/com/grepp/nbe1_3_team04/config/redis/ExternalRedisConfig.kt
Labels: ✨Feature, 황민우

#85 [Refactor/#78] 풋살장 위치 관련 리펙토링
  build.gradle.kts
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/domain/Court.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/domain/Position.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/domain/Stadium.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/repository/CustomStadiumRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/repository/CustomStadiumRepositoryImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/repository/StadiumRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/service/CourtServiceImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/service/StadiumServiceImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/service/response/StadiumDetailResponse.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/stadium/util/PositionUtil.kt
Labels: ✨Feature, 🔨Refactor, 노관태

#86 [Fix/#82] 팀 관련 버그 수정
  src/main/kotlin/com/grepp/nbe1_3_team04/team/repository/TeamMemberRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/team/service/TeamMemberServiceImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/team/service/TeamServiceImpl.kt
Labels: 🔥BugFix, 박윤영
