Repository prgrms-be-devcourse/NBB1_1_3_Team04, pull requests merged in 2024-11, with the labels that each got.

#87 [Feat/#83] security bug fix
  src/main/kotlin/com/grepp/nbe1_3_team04/config/SecurityConfig.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/global/exception/filter/CustomAccessDeniedHandler.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/global/exception/filter/CustomAuthenticationEntryPoint.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/global/exception/filter/ExceptionHandlerFilter.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/api/MemberApi.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/api/request/JoinRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/api/request/UpdatePasswordRequest.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/jwt/JwtTokenFilter.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/jwt/JwtTokenUtil.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/oauth2/handler/CustomOAuth2LoginFailureHandler.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/member/oauth2/handler/CustomOAuth2LoginSuccessHandler.kt
Labels: 🔥BugFix, 문재경

#89 [Refactor/#88] GameServiceImpl 리펙토링
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/domain/Game.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/domain/GameStatus.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/domain/Reservation.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/repository/ReservationRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/reservation/service/GameServiceImpl.kt
Labels: 🔨Refactor, 노관태

#90 [Feat/#84] 채팅 redis 캐싱 및 벌크 인서트 구현
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/api/ChatApi.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/api/ChatMemberApi.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/api/ChatroomApi.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/repository/ChatJDBCRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/repository/ChatRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/repository/CustomChatRepository.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/repository/CustomChatRepositoryImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/ChatMemberServiceImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/ChatService.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/ChatServiceImpl.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/chat/service/response/ChatResponse.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/config/redis/RedisConfig.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/global/domain/BaseEntity.kt
  src/main/kotlin/com/grepp/nbe1_3_team04/global/exception/ExceptionMessage.kt
Labels: ✨Feature, 황민우
